[package]
name = "wasm-math"
version = "0.1.0"
authors = ["liaodh <liaodh@jiguang.cn>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.33"
js-sys = "0.3.10"

[profile.release]
opt-level = 3
